# Generated by Django 2.2 on 2019-07-20 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_zhumodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        # migrations.AddField(
        #     model_name='commodel',
        #     name='bao',
        #     field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='BAO', to='core.BaoModel'),
        #     preserve_default=False,
        # ),
    ]
