# Generated by Django 2.2 on 2019-07-20 02:38

from django.db import migrations


def forwards_func(apps, schema_editor):
    BaoModel = apps.get_model("core", "BaoModel")
    db_alias = schema_editor.connection.alias
    BaoModel.objects.using(db_alias).bulk_create([
        BaoModel(age=28, address="liuying"),
        BaoModel(age=27, address="baoshan"),
    ])


def reverse_func(apps, schema_editor):
    BaoModel = apps.get_model("core", "models.BaoModel")
    db_alias = schema_editor.connection.alias
    BaoModel.objects.using(db_alias).filter(age=28).filter(name="liuying").delete()
    BaoModel.objects.using(db_alias).filter(age=27).filter(name="baoshan").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190720_1001'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
