# Generated by Django 2.2 on 2019-07-20 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190720_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodel',
            name='bao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='BAO', to='core.BaoModel'),
        ),
    ]
